const express = require('express')
const { dashboard, AdminLoginPage, adminAuthCheck, AdminLogin, logout, getAllBlogs, deleteBlog, getContacts, updateBlog, create_banner, update_banner, delete_banner, create_care, care, update_care, delete_care, testimonial, create_testimonial, update_testimonial, delete_testimonial, banner, feature, create_features, editFeature, deleteFeature, partner, createPartner, editPartner, deletePartner, getAboutHome, createAboutSection, editAboutSection, deleteAboutSection, getSectionAbout, createSectionAbout, updateSectionAbout, deleteSectionAbout, getFeatureAbout, createFeatureAbout, editFeatureAbout, deleteFeatureAbout, getAwards, createAwards, editAwards, deleteAwards, getSpecialists, getSectionTestimonial, create_SectionTestimonial, update_SectionTestimonial, delete_SectionTestimonial, getServices, createService, editService, deleteService, getSectionCta, createCta, editCta, deleteCta, getFooter, createFooter, editFooter, getDepartments, createDepartment, editDepartment, deleteDepartment, deleteFooter, getDoctors, createDoctor, editDoctor, deleteDoctor, createBlog, getComments, deleteComment, replyToComment, deleteReply, getHospitalContact, createHospitalContact, editHospitalContact, deleteHospitalContact, activeBlog, deactiveBlog, getUsers, activeUser, deactiveUser, getTitlePage, createTitleSection, editTitleSection, deleteTitleSection } = require('../controller/AdminController')
const { jwtAuth } = require('../middleware/adminAuth')
const Upload = require('../utils/Image')
const Router = express.Router()

//routes
Router.use(jwtAuth)

Router.get('/dashboard', adminAuthCheck, dashboard)
Router.get('/loginView', AdminLoginPage)
Router.post('/login', AdminLogin)
Router.get('/logout', adminAuthCheck, logout)
Router.get('/users', adminAuthCheck, getUsers)
Router.get('/activate/user/:id', adminAuthCheck, activeUser)
Router.get('/deactivate/user/:id', adminAuthCheck, deactiveUser)
Router.get('/footer',adminAuthCheck, getFooter)
Router.post('/footer/create', Upload.single('logo'),adminAuthCheck, createFooter)
Router.post('/footer/edit/:id', Upload.single('logo'),adminAuthCheck, editFooter)
Router.post('/footer/delete/:id',adminAuthCheck, deleteFooter)
Router.get('/contact', adminAuthCheck, getContacts)
Router.get('/banner',adminAuthCheck, banner)
Router.post('/create-banner', Upload.single('image'), adminAuthCheck, create_banner)
Router.post('/update-banner/:id', Upload.single('image'), adminAuthCheck, update_banner)
Router.post('/delete-banner/:id',adminAuthCheck, delete_banner)
Router.get('/features',adminAuthCheck, feature)
Router.post('/create-feature',adminAuthCheck, create_features)
Router.post('/edit-feature/:id',adminAuthCheck, editFeature)
Router.post('/delete-feature/:id',adminAuthCheck, deleteFeature)
Router.get('/care',adminAuthCheck, care)
Router.post('/create-service',adminAuthCheck, create_care)
Router.post('/update-service/:id',adminAuthCheck, update_care)
Router.post('/delete-service/:id',adminAuthCheck, delete_care)
Router.get('/patient-review',adminAuthCheck, testimonial)
Router.post('/create-testimonial', Upload.single('image'),adminAuthCheck, create_testimonial)
Router.post('/update-testimonial/:id', Upload.single('image'),adminAuthCheck, update_testimonial)
Router.post('/delete-testimonial/:id',adminAuthCheck, delete_testimonial)
Router.get('/partner',adminAuthCheck, partner)
Router.post('/create-partner', Upload.single('image'),adminAuthCheck, createPartner)
Router.post('/edit-partner/:id', Upload.single('image'),adminAuthCheck, editPartner)
Router.post('/delete-partner/:id',adminAuthCheck, deletePartner)
Router.get('/about-home',adminAuthCheck, getAboutHome)
Router.post('/create-aboutSection', Upload.array('images', 3),adminAuthCheck, createAboutSection)
Router.post('/edit-aboutSection/:id', Upload.array('images', 3),adminAuthCheck, editAboutSection)
Router.post('/delete-aboutSection/:id',adminAuthCheck, deleteAboutSection)
Router.get('/section-about',adminAuthCheck, getSectionAbout)
Router.post('/create-SectionAbout', Upload.single('image'),adminAuthCheck, createSectionAbout)
Router.post('/edit-SectionAbout/:id', Upload.single('image'),adminAuthCheck, updateSectionAbout)
Router.post('/delete-SectionAbout/:id', Upload.single('image'),adminAuthCheck, deleteSectionAbout)
Router.get('/feature-about',adminAuthCheck, getFeatureAbout)
Router.post('/create-featureAbout', Upload.single('image'),adminAuthCheck, createFeatureAbout)
Router.post('/edit-featureAbout/:id', Upload.single('image'),adminAuthCheck, editFeatureAbout)
Router.post('/delete-featureAbout/:id', Upload.single('image'),adminAuthCheck, deleteFeatureAbout)
Router.get('/achievements',adminAuthCheck, getAwards)
Router.post('/create-awards', Upload.single('image'), adminAuthCheck, createAwards)
Router.post('/edit-awards/:id', Upload.single('image'),adminAuthCheck, editAwards)
Router.post('/delete-awards/:id',adminAuthCheck, deleteAwards)
Router.get('/specialists',adminAuthCheck, getSpecialists)
Router.get('/section-testimonial',adminAuthCheck, getSectionTestimonial)
Router.post('/create-sectionTestimonial', Upload.single('image'),adminAuthCheck, create_SectionTestimonial)
Router.post('/update-sectionTestimonial/:id', Upload.single('image'),adminAuthCheck, update_SectionTestimonial)
Router.post('/delete-sectionTestimonial/:id',adminAuthCheck, delete_SectionTestimonial)
Router.get('/service',adminAuthCheck, getServices)
Router.post('/service/create', Upload.single('image'),adminAuthCheck, createService)
Router.post('/edit/service/:id', Upload.single('image'),adminAuthCheck, editService)
Router.post('/delete/service/:id',adminAuthCheck, deleteService)
Router.get('/cta',adminAuthCheck, getSectionCta)
Router.post('/cta/create', Upload.single('image'),adminAuthCheck, createCta)
Router.post('/cta/edit/:id', Upload.single('image'),adminAuthCheck, editCta)
Router.post('/cta/delete/:id',adminAuthCheck, deleteCta)
Router.get('/departments',adminAuthCheck, getDepartments)
Router.post('/department/create', Upload.single('image'),adminAuthCheck, createDepartment)
Router.post('/department/edit/:id', Upload.single('image'),adminAuthCheck, editDepartment)
Router.post('/department/delete/:id',adminAuthCheck, deleteDepartment)
Router.get('/doctors',adminAuthCheck, getDoctors)
Router.post('/doctor/create', Upload.single('image'),adminAuthCheck, createDoctor)
Router.post('/doctor/edit/:id', Upload.single('image'),adminAuthCheck, editDoctor)
Router.post('/doctor/delete/:id',adminAuthCheck, deleteDoctor)
Router.get('/AllBlogs', adminAuthCheck, getAllBlogs)
Router.post('/blog/create', Upload.single('image'), adminAuthCheck, createBlog)
Router.post('/update_blog/:id', Upload.single('image'), adminAuthCheck, updateBlog )
Router.post('/deleteBlog/:id', adminAuthCheck, deleteBlog)
Router.get('/activeBlog/:id', adminAuthCheck, activeBlog)
Router.get('/deactiveBlog/:id', adminAuthCheck, deactiveBlog)
Router.get('/comments', adminAuthCheck, getComments)
Router.post('/delete/comment/:id', adminAuthCheck, deleteComment)
Router.post('/comment/:id/reply', adminAuthCheck, replyToComment)
Router.post('/comments/:commentId/replies/:replyId', adminAuthCheck, deleteReply)
Router.get('/hospitalContact', adminAuthCheck, getHospitalContact)
Router.post('/hospitalContact/create', adminAuthCheck, createHospitalContact)
Router.post('/hospitalContact/edit/:id', adminAuthCheck, editHospitalContact)
Router.post('/hospitalContact/delete/:id', adminAuthCheck, deleteHospitalContact)
Router.get('/title', adminAuthCheck, getTitlePage)
Router.post('/title/create', Upload.single('image'), adminAuthCheck, createTitleSection)
Router.post('/title/update/:id', Upload.single('image'), adminAuthCheck, editTitleSection)
Router.post('/title/delete/:id', adminAuthCheck, deleteTitleSection)



module.exports = Router